name: ip_localizacao
description: Uma biblioteca para consulta da localização do IP externo para desenvolvedores Dart (Console, Web e Flutter).
version: 1.0.0
homepage: https://debugging.com.br/
repository: https://github.com/mateuspenha/ip_location
issue_tracker: https://github.com/mateuspenha/ip_location/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ip_externo: ^1.0.3
  http: ^0.12.0+1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0